### ISSUE TITLE
弹幕加载失败

### ISSUE THREAD

**Issue by Puxirepublic** [Protostars/KikoPlay-Android-LAN#1]
Win 端最新版，apk 下的也是最新版，设置里打开 lan，读取播放列表，播放视频一切正常，唯独不读取弹幕，显示弹幕加载失败。
Win 端的 lan log 显示和预览截图一致，没有其他错误信息。
手机是原生 Android 13。

**Comment by Protostars** [comment]
Pc端有弹幕吗？如果是本地加载的弹幕，需要你把它加入到弹幕池里，你也可以从浏览器打开web端确认一下

**Comment by Puxirepublic** [comment]
> Pc端有弹幕吗？如果是本地加载的弹幕，需要你把它加入到弹幕池里，你也可以从浏览器打开web端确认一下

有弹幕，是本地加载的弹幕，无论手动加载还是跟播放视频同目录下同名自动加载，都能正常显示弹幕。
web 端也是不显示弹幕。

**Comment by Protostars** [comment]
所以目前你需要手动添加到弹幕池，这个地方后面会改进一下

**Comment by Puxirepublic** [comment]
> 所以目前你需要手动添加到弹幕池，这个地方后面会改进一下

原来如此，是指手动关联进弹幕池管理器里。现在一切都正常了。
